[package]
name = "solana-verify"
version = "0.2.8"
edition = "2021"
description = "A CLI tool for building verifiable Solana programs"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
anyhow = "1.0.68"
tokio = { version = "1.29.1", features = ["full"] }
solana-client = "1.14.10"
solana-cli-config = "1.14.10"
solana-sdk = "1.14.10"
sha256 = "1.1.1"
hex = "0.3.1"
serde_json = "1.0"
cargo_toml = "0.15.3"
pathdiff = "0.2.0"
signal-hook = "0.3.15"
reqwest = "0.11.18"
cargo-lock = "9.0.0"
lazy_static = "1.4.0"
indicatif = "0.17.7"
crossbeam-channel = "0.5.11"
serde = { version = "1.0.166", features = ["derive"] }

[dependencies.uuid]
version = "1.2.2"
features = [
    "v4",                # Lets you generate random UUIDs
    "fast-rng",          # Use a faster (but still sufficiently random) RNG
    "macro-diagnostics", # Enable better diagnostics for compile-time UUIDs
]
