[package]
name = "verifier-cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
anyhow = "1.0.68"
cmd_lib = "1.3.0"
solana-client = "1.14.10"
solana-sdk = "1.14.10"
sha256 = "1.1.1"
hex = "0.3.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
toml = "0.7.1"
